repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/ambv/black
    rev: 21.4b2
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        args: ["--ignore=ANN001,ANN101,ANN002,W503", --max-line-length=88]
        additional_dependencies:
          - flake8-annotations

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: local
    hooks:
      - id: export-requirements
        name: export-requirements
        entry: poetry export
        language: system
        always_run: true
        pass_filenames: false
        args: ["-f", "requirements.txt", "--output", "requirements.txt"]
